야후 파이낸스의 sp500 주식 데이터를 다운로드하여 CSV 파일을 읽음
csv 혹은 pandas로 읽을 수 있음

In [1]:
import pandas

stock = pandas.read_csv('GSPC.csv') # pandas는 고수준으로 파일 처리가 편함
stock.shape                         # 251개의 행에 7개의 열

(251, 7)

In [53]:
import numpy as np

arr = np.array(stock)       # 배열로 변환
arr.shape

(251, 7)

In [5]:
arr[0] # 첫번째 행을 꺼내라  arr[0] == arr[0,:]

array(['2018-06-18', 2765.790039, 2774.98999, 2757.1201170000004, 2773.75,
       2773.75, 3287150000], dtype=object)

In [6]:
arr[0,0], arr[-1,-1] # 첫번째 행의 첫번째 열 # 마지막 행의 마지막 열 

('2018-06-18', 1579314342)

In [7]:
o  = arr[:,1]   # Open 만 가져오자 : Date	Open	High	Low	Close	Adj Close	Volume
o

array([2765.790039, 2752.01001, 2769.72998, 2769.280029, 2760.790039,
       2742.939941, 2722.1201170000004, 2728.449951, 2698.689941,
       2727.1298829999996, 2704.949951, 2733.27002, 2724.189941,
       2737.679932, 2775.6201170000004, 2788.560059, 2779.820068,
       2783.139893, 2796.929932, 2797.360107, 2789.340088, 2811.350098,
       2809.3701170000004, 2804.550049, 2799.169922, 2820.679932,
       2817.72998, 2835.48999, 2842.350098, 2819.0, 2809.72998,
       2821.169922, 2800.47998, 2829.6201170000004, 2840.290039,
       2855.919922, 2856.790039, 2857.189941, 2838.899902, 2835.459961,
       2827.8798829999996, 2827.949951, 2831.439941, 2838.320068,
       2853.929932, 2861.51001, 2860.98999, 2860.290039, 2862.350098,
       2884.689941, 2901.449951, 2900.6201170000004, 2908.939941,
       2898.3701170000004, 2896.959961, 2891.590088, 2888.639893,
       2868.26001, 2881.389893, 2871.570068, 2888.290039, 2896.850098,
       2906.3798829999996, 2903.830078, 2890.73999, 290

In [8]:
# Close 만 가져오자 : Date	Open	High	Low	Close	Adj Close	Volume
close = arr[:,-3]  # 편함 # => close = arr[:,4] 도 가능
#close

In [9]:
# b(below) 아래쪽에 셀 만들기
# open의 최대값, 최소값, 평균을 구함
# 내장 함수 : import 없이 바로 사용가능한 함수
# 통계치, 평균, 중간값, 표준편차
max(o), min(o), np.max(o), np.min(o), np.mean(o), np.median(o), np.std(o)

(2952.330078,
 2363.1201170000004,
 2952.330078,
 2363.1201170000004,
 2780.9741113346613,
 2799.169922,
 113.36175052380939)

In [10]:
# Open	High	Low	Close 4개의 컬럼만 뽑자
v4 = arr[:,1:5]
v4.shape

(251, 4)

In [54]:
np.max(v4, axis=0)

array([2952.330078, 2954.1298829999996, 2939.350098, 2945.830078],
      dtype=object)

In [55]:
np.max(v4, axis=1)

array([2774.98999, 2765.050049, 2774.860107, 2769.280029, 2764.169922,
       2742.939941, 2732.909912, 2746.090088, 2724.340088, 2743.26001,
       2727.26001, 2736.580078, 2737.830078, 2764.409912, 2784.649902,
       2795.580078, 2785.909912, 2799.219971, 2804.530029, 2801.189941,
       2814.189941, 2816.76001, 2812.050049, 2809.699951, 2808.610107,
       2829.98999, 2848.030029, 2845.570068, 2843.169922, 2821.73999,
       2824.459961, 2825.830078, 2829.909912, 2840.3798829999996,
       2853.290039, 2863.429932, 2862.439941, 2862.47998, 2842.199951,
       2843.399902, 2843.110107, 2827.949951, 2850.48999,
       2855.6298829999996, 2859.76001, 2873.22998, 2867.540039,
       2868.780029, 2876.159912, 2898.25, 2903.77002, 2916.5, 2912.459961,
       2906.320068, 2900.179932, 2894.209961, 2892.050049, 2883.810059,
       2886.929932, 2892.52002, 2894.649902, 2906.76001, 2908.300049,
       2904.649902, 2911.169922, 2912.360107, 2934.800049, 2940.909912,
       2923.790039, 2923.9

In [14]:
# argmax, argmin 맥스값의 위치
np.max(o), np.argmax(o)

(2952.330078, 218)

주가가 가장 많이 상승한 날짜 찾기 (정답 : x번째 행)
(종가 -시가)이 가장 큰 날

In [46]:
close_v = arr[:,-3]
open_v = arr[:,1]
day_v = arr[:,0]
vol = arr[:,-1]
gap = close_v - open_v

In [37]:
#np.max(close_v - open_v)
np.max(gap), np.argmax(gap), day_v[np.argmax(gap)]

(104.57983399999966, 132, '2018-12-26')

#### 데이터 분석
- 가격 상승하는 날 거래량이 많아질까?
- 전날 가격이 상승하면 다음날 시작가격은 더 높은 가격에서 시작할까?
- 가격 변동이 크면 거래량도 많아질까?

##### 다음 단계 : 예측
- 어제/오늘 현황 분석이 끝났는데 내일은 Open/Close 이 어떻게 될까?
- 방법 : 1. 통계적 방법(R), 2. 머신러닝

In [51]:
# 상승한 날의 거래량 / 하락한 날의 거래량
np.mean(vol[gap > 0]), np.mean(vol[gap < 0])

(3513170514.7058825, 3663782472.53913)

In [52]:
# 가격 상승하는 날 거래량이 많아질까?
np.mean(vol[gap > 0]) > np.mean(vol[gap < 0])

False

In [32]:
# 조건부 검색
a = np.array([1,2,3,4])
even = a%2==0 # 짝수값만 뽑고 싶다.
even #  불린 마스크

array([False,  True, False,  True])

In [33]:
# 불린 마스크를 인덱스로 사용하면 True값 만 뽑힘
a[even]

array([2, 4])

In [68]:
np.zeros(shape=(4))

array([0., 0., 0., 0.])

In [66]:
np.zeros(shape=(3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
np.zeros(shape=(2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [56]:
np.zeros(shape=(2,3,4), dtype=np.int32)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [70]:
np.zeros(shape=(3,2,5), dtype=np.int32) 

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [72]:
np.full((3,2,4),2.1)

array([[[2.1, 2.1, 2.1, 2.1],
        [2.1, 2.1, 2.1, 2.1]],

       [[2.1, 2.1, 2.1, 2.1],
        [2.1, 2.1, 2.1, 2.1]],

       [[2.1, 2.1, 2.1, 2.1],
        [2.1, 2.1, 2.1, 2.1]]])

In [77]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [76]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [78]:
# zeros > ones > arange 많이 쓰는 순서

In [82]:
np.linspace(0,30,5) # 시작값, 끝값, x 등분

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [87]:
import random
random.randint(1,10)

3

In [91]:
np.random.rand(2,3) #대부분의 random 함수는 0~1사이 값이 나옴[0,1]

array([[0.97236163, 0.23546606, 0.84536635],
       [0.43225291, 0.85882457, 0.96630612]])

In [92]:
np.random.normal(size=(2,3))   # 정모양의(평균값)의 정규 분포, 평균값이 많이 나옴

array([[ 0.82560376,  1.4743442 ,  1.30273824],
       [-0.47770279, -0.62374305,  0.32703397]])

In [93]:
np.random.randint(low=1, high=10, size=(2,3))

array([[8, 3, 1],
       [2, 8, 9]])

In [94]:
np.random.uniform(size=(2,3)) # 전체값에서 균등하게 나옴. 제어가능

array([[0.35174038, 0.09709122, 0.52646384],
       [0.80340241, 0.97565086, 0.12324298]])

In [100]:
a = np.ones(shape=(3,5))
b = np.ones(shape=(3,2))
a+b

ValueError: operands could not be broadcast together with shapes (3,5) (3,2) 

In [101]:
# 예외케이스 broadcasting(모양이 같아야 함)
a = np.ones(shape=(3,2))
b = np.ones(shape=(3,1))  
a+b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [102]:
# 예외케이스 broadcasting(모양이 같아야 함)
a = np.ones(shape=(3,2), dtype=np.int)
b = np.ones(shape=(3,2), dtype=np.float)  
a+b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [105]:
# 행우선으로 저장됨
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [107]:
b = a.reshape((2,3))
b
'''
Fortran, R언어은 열우선(열방향)으로 저장됨
[[0,3]
 [1,4]
 [2,5]]
'''

'\nFortran, R언어은 열우선(열방향)으로 저장됨\n[[0,3]\n [1,4]\n [2,5]]\n'

In [110]:
# 차원 갯수, *모양*,  총요소 갯수, 데이터 타입, 메모리 사용량
b.ndim,      b.shape, b.size,      b.dtype,     b.nbytes

(2, (2, 3), 6, dtype('int32'), 24)

In [111]:
b.flatten() # 1차원으로 변환 flatten:평면화

array([0, 1, 2, 3, 4, 5])

In [115]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 데이타 자르기 : slicing
- [1,4,7]
- [6,7,8]
- [1,2,4,5,6,7]
- [4,5,7,8]


In [124]:
a[:,1], a[2,:], a[:,1:].flatten(), a[1:,1:].flatten()

(array([1, 4, 7]),
 array([6, 7, 8]),
 array([1, 2, 4, 5, 7, 8]),
 array([4, 5, 7, 8]))

In [126]:
b = np.arange(12).reshape((3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# b에서 아래 요소/원소(element)를 잘라(slice) 주세요
- [ 5,  6,  9, 10]
- [ 9, 10, 11]

In [131]:
b[1:,1:3].flatten(), b[1:,1:-1].flatten(), b[-1,1:]  

(array([ 5,  6,  9, 10]), array([ 5,  6,  9, 10]), array([ 9, 10, 11]))

In [143]:
# 3차원
c = np.arange(2*3*4).reshape((2,3,4))
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [140]:
 c[0] 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [146]:
 c[0,0,:], c[1,0], c[0, :, 1], c[1,:,-1]

(array([0, 1, 2, 3]),
 array([12, 13, 14, 15]),
 array([1, 5, 9]),
 array([15, 19, 23]))

In [150]:
c[0,1:,-2], c[1,1,1:], c[1,:-1,1:-1].flatten()

(array([ 6, 10]), array([17, 18, 19]), array([13, 14, 17, 18]))

In [154]:
c.shape
c.reshape((4,6)),np.reshape(c,(8,3))

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

In [161]:
c.size, c.reshape((6,-1)), c.reshape((-1,8)) # -1은 알아서 맞춰라. 1번만 사용

(24, array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]))

In [222]:
np.arange(12,18)

array([12, 13, 14, 15, 16, 17])

In [223]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
a_1= np.arange(12,18).reshape(2,3)
b_1= np.arange(18,24).reshape(2,3)
a,b

(array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]]))

In [224]:
# 두 배열을 붙임니다. concatenate == concat
c = np.concatenate((a,b,a),axis=0)  # axis=0 이면 행으로 추가
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [173]:
a.shape, c.shape

((2, 3), (6, 3))

In [177]:
# 두 배열을 붙임니다. concatenate == concat
d = np.concatenate((a,b,a),axis=1)  # axis=1 이면 열로 추가
d

array([[ 0,  1,  2,  6,  7,  8,  0,  1,  2],
       [ 3,  4,  5,  9, 10, 11,  3,  4,  5]])

In [176]:
a.shape, b.shape, c.shape, d.shape

((2, 3), (2, 3), (6, 3), (2, 9))

In [ ]:
#  예
data1 = file1.csv
data2 = file2.csv
data = np.concatenate((data1, data2), axis=0)

In [225]:
# Stack 쌓다 , axis를 지정한 곳에 배열들이 쌓임.
c = np.stack((a,b,a_1,b_1), axis=0)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [188]:
a.shape, b.shape, c.shape

((2, 3), (2, 3), (4, 2, 3))

In [226]:
d = np.stack((a,b,a_1,b_1), axis=1)
d

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]]])

In [190]:
a.shape, b.shape, c.shape, d.shape

((2, 3), (2, 3), (2, 4, 3))

In [227]:
e = np.stack((a,b,a_1,b_1), axis=2) # 쌓으면 차원이 1 증가함.
e

array([[[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20]],

       [[ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]]])

In [192]:
a.shape, b.shape, c.shape, d.shape, e.shape

((2, 3), (2, 3), (4, 2, 3), (2, 4, 3), (2, 3, 4))

In [194]:
# Stack 활용 예
#[첫번째 학생, 두번째 학생, 세번째 학생]
kor = [80,90,99]
eng = [70,50,60]
score = np.stack((kor, eng), axis=1)
score

array([[80, 70],
       [90, 50],
       [99, 60]])

In [196]:
math = [20,30,40]
score1 = np.stack((kor,eng,math), axis=1)
score1

array([[80, 70, 20],
       [90, 50, 30],
       [99, 60, 40]])

In [205]:
math_n = np.array([20,30,40]).reshape((3,1))
math_n

array([[20],
       [30],
       [40]])

In [206]:
score2 = np.concatenate((score,math_n), axis=1)
score2 = np.concatenate((score,math_n), axis=-1) # -1은 마지막열을 가리킴
score2

array([[80, 70, 20],
       [90, 50, 30],
       [99, 60, 40]])

In [202]:
# 4번째 학생의 국영수 점수가 추가됐음
student_4 = np.array([100,90,90]).reshape((1,3))
student_4

array([[100,  90,  90]])

In [229]:
score3 = np.concatenate((score2,student_4), axis=0)
score3

array([[ 80,  70,  20],
       [ 90,  50,  30],
       [ 99,  60,  40],
       [100,  90,  90]])

In [230]:
score3.shape

(4, 3)

In [216]:
# 각 과목별 평균은?
np.mean(score3, axis=0)

array([92.25, 67.5 , 45.  ])

In [219]:
# 학생의 평균 점수는?
np.mean(score3, axis=1)

array([56.66666667, 56.66666667, 66.33333333, 93.33333333])

In [218]:
# 시험을 가장 잘 본 학생의 평균 점수는?
np.max(np.mean(score3, axis=1))

93.33333333333333

In [233]:
# np.save() : Save an array to a binary file in NumPy ``.npy`` format.
# Save an array to a text file., %.18e, %10.5f : 소수 5째자리까지 저장(default)
np.savetxt('score_sample1.txt',score3) # 소수점 18개까지
np.savetxt('score_sample.txt',score3, '%d') # 포맷은 정수로 저장

In [237]:
# read, open, load
s = np.loadtxt('score_sample.txt')          # 기본 타입 : float
s1 = np.loadtxt('score_sample.txt',dtype='int32')   # 타입 설정 : int32
s, s1

(array([[ 80.,  70.,  20.],
        [ 90.,  50.,  30.],
        [ 99.,  60.,  40.],
        [100.,  90.,  90.]]), array([[ 80,  70,  20],
        [ 90,  50,  30],
        [ 99,  60,  40],
        [100,  90,  90]]))

In [239]:
s[:]    # s[:] == s[:,:]

array([[ 80.,  70.,  20.],
       [ 90.,  50.,  30.],
       [ 99.,  60.,  40.],
       [100.,  90.,  90.]])

In [240]:
s[:, ::-1]  # 시작부터 끝까지 거꾸로

array([[ 20.,  70.,  80.],
       [ 30.,  50.,  90.],
       [ 40.,  60.,  99.],
       [ 90.,  90., 100.]])

In [241]:
s[:, ::2]  # 시작부터 끝까지 2 스템(간격)으로 출력

array([[ 80.,  20.],
       [ 90.,  30.],
       [ 99.,  40.],
       [100.,  90.]])

In [243]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [249]:
# 시작부터 끝까지 2칸씩 뛰면서 = 짝수
# 1번째 요소부터 끝까지 2칸씩 뛰면서 = 홀수
# 2번째 요소부터 6번째 요소까지 2칸씩 뛰면서
# [시작:끝:간격] 생략하면 기본값 시작=0, 끝=끝, 간격=1(-1은 반대로)
a[::2], a[1::2], a[2:6:2], a[4::-2]

(array([0, 2, 4, 6, 8]),
 array([1, 3, 5, 7, 9]),
 array([2, 4]),
 array([4, 2, 0]))

In [251]:
# 분리하기, index의 복수 = indices 3, 5, 8의 위치로 분리(자름)
np.split(a,[3,5,8])

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7]), array([8, 9])]

In [253]:
# 분리하기 section 갯수로 자르기 => a의 배열을 5개로 나누기  
# 머신러닝에서 데이터 셋을 k개 분리해서 k-flod validation set을 만듦
# k = 3 이라면, 데이터를 3개로 분리해서 2개 셋은 학습, 1개 셋은 테스트로 사용
'''
3-flod validation set
ABC
학습 : AB / 테스트 : C
학습 : BC / 테스트 : A
학습 : AC / 테스트 : B
'''
np.split(a,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [254]:
# 분리하기 section 갯수로 자르기 => a의 배열을 2개로 나누기
np.split(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

### 브로드 캐스팅
- 배열의 모양이 서로 다를 때 연산이 가능하게 해주는 기능

In [255]:
a * 2 # 브로드 캐스팅이 적용되어서 연산 가능

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [257]:
a = np.array([0,10,20,30])
a = np.stack((a,a,a),1)      # np.repeat, np.tile로 배열 복제 가능
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [258]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [259]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [267]:
c = np.array([0,10,20,30]).reshape(4,1)
c+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [268]:
# 강사의 예시
d = np.arange(4)*10
d = d.reshape([-1,1])  
e = np.arange(3)
d.shape, e.shape

((4, 1), (3,))

In [270]:
# 브로드 캐스팅
d + e, d * e

(array([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]]), array([[ 0,  0,  0],
        [ 0, 10, 20],
        [ 0, 20, 40],
        [ 0, 30, 60]]))

비교 > < == >=

In [271]:
7 == 3

False

In [276]:
a = np.arange(8)
b = np.arange(1,3)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [277]:
mask = a > 2
mask

array([False, False, False,  True,  True,  True,  True,  True])

In [278]:
# True 인 값만 선택됩니다. boolean mask 를 이용한 indexing
a[mask]

array([3, 4, 5, 6, 7])

In [282]:
n_mask = np.logical_not(mask)
n_mask

array([ True,  True,  True, False, False, False, False, False])

In [284]:
np.logical_and(mask, mask)

array([False, False, False,  True,  True,  True,  True,  True])

In [289]:
# 짝수이면서 2보다 큰 값을 뽑으세요. logical_and, [mask]를 이용
mask0 = a % 2 == 0
mask1 = a > 2
mask2 = np.logical_and(mask0, mask1)
a[mask2]

array([4, 6])

In [293]:
# 정렬
np.sort(a),a[::-1]

(array([0, 1, 2, 3, 4, 5, 6, 7]), array([7, 6, 5, 4, 3, 2, 1, 0]))