### 7장 텍스트 데이터 만들기

In [21]:
sentences = ['가장 자연스럽고 좋은 영화 였다',
            '최고의 영화 4편이 기대됨']
sentences = ['정말 재미있게 아이와 끝까지 봤습니다',
             '항상 아이와 보면 중간에 아이가 나가자고 조르는데 끝까지 본 두번째 영화',
             '너무 재밌어서 2번이나 보고 또 보고 싶다고 생각든 영화',
             '두번째 볼때가 더 재밌어요 배우들의 표정 제스처 세트 소품 퀄리티 돋보임',
             '어느새 감동 받아 눈물 흘렸어요']

In [22]:
type(sentences), len(sentences)

(list, 5)

##### BOW(Bag of Words) 단어 가방으로 전처리

In [12]:
# 420
from sklearn.feature_extraction.text import CountVectorizer # 갯수를 세어서 배열로 만든다.

In [13]:
vect = CountVectorizer()

In [23]:
vect.fit(sentences)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [24]:
len(vect.vocabulary_), vect.vocabulary_

(33,
 {'정말': 25,
  '재미있게': 22,
  '아이와': 19,
  '끝까지': 2,
  '봤습니다': 13,
  '항상': 31,
  '보면': 11,
  '중간에': 28,
  '아이가': 18,
  '나가자고': 3,
  '조르는데': 27,
  '두번째': 7,
  '영화': 21,
  '너무': 4,
  '재밌어서': 23,
  '2번이나': 0,
  '보고': 10,
  '싶다고': 17,
  '생각든': 14,
  '볼때가': 12,
  '재밌어요': 24,
  '배우들의': 9,
  '표정': 30,
  '제스처': 26,
  '세트': 15,
  '소품': 16,
  '퀄리티': 29,
  '돋보임': 6,
  '어느새': 20,
  '감동': 1,
  '받아': 8,
  '눈물': 5,
  '흘렸어요': 32})

In [25]:
# dense_matrix <-> sparse_matrix(자연어) : 메모리 절약하기 위해 사용
sparse_matrix = vect.transform(sentences)  # 자연어를 BOW로 변환
sparse_matrix

<5x33 sparse matrix of type '<class 'numpy.int64'>'
	with 37 stored elements in Compressed Sparse Row format>

In [26]:
sparse_matrix.toarray() # sparse_matrix를 dense로 변환

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [27]:
sentences

['정말 재미있게 아이와 끝까지 봤습니다',
 '항상 아이와 보면 중간에 아이가 나가자고 조르는데 끝까지 본 두번째 영화',
 '너무 재밌어서 2번이나 보고 또 보고 싶다고 생각든 영화',
 '두번째 볼때가 더 재밌어요 배우들의 표정 제스처 세트 소품 퀄리티 돋보임',
 '어느새 감동 받아 눈물 흘렸어요']

# 뉴스 Dataset을 분류하기

In [168]:
from sklearn.datasets import fetch_20newsgroups

In [169]:
news = fetch_20newsgroups()  # Download 진행

In [170]:
len(news.data), len(news.target_names)

(11314, 20)

In [174]:
type(news)

sklearn.utils.Bunch

In [34]:
print(news.data[0])

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----







In [35]:
news.target[0], news.target_names[0]

(7, 'alt.atheism')

### 뉴스의 텍스트를 활용하여 교차학습하기

- 자연어 뉴스를 배열(vector)로 변환/BOW

In [167]:
vect = CountVectorizer()   # 단어 분류

In [37]:
vect.fit(news.data) 

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [39]:
len(vect.vocabulary_)

130107

In [41]:
sm = vect.transform(news.data)
sm

<11314x130107 sparse matrix of type '<class 'numpy.int64'>'
	with 1787565 stored elements in Compressed Sparse Row format>

In [42]:
from sklearn.linear_model import LogisticRegression

In [45]:
model = LogisticRegression().fit(sm, news.target)

C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [46]:
model.score(sm, news.target)

0.999734841788934

In [57]:
test_set = ['Hi, Major Leagure. who is winner? ','I want to buy a noteboot. where should I go? ']

In [58]:
model.predict(vect.transform(test_set))

array([15,  4])

In [68]:
news.target_names[15], news.target_names[4], news.target

('soc.religion.christian',
 'comp.sys.mac.hardware',
 array([7, 4, 4, ..., 3, 1, 8]))

In [61]:
sm_test = vect.transform(test_set)
dm = sm_test[0].toarray()
dm.shape

(1, 130107)

In [63]:
sm_test[0].indices # indexes 배열의 크기가 너무 크기 때문에 0이 아닌 값이 있는 위치를 볼 수 밖에 없음.

array([ 63092,  68532,  79043, 124147, 124501])

In [65]:
import numpy as np
np.sum(dm), dm

(5, array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64))

# 파이썬 한글 형태소 분석기 다운로드
- https://blog.naver.com/koys007/221460757885
- https://www.lfd.uci.edu/~gohlke/pythonlibs/#jpype
  - (JPype1‑0.7.0‑cp37‑cp37m‑win_amd64.whl) 다운로드 받아서 아나콘다 콘솔에서 설치(pip install JPype1‑0.7.0‑cp37‑cp37m‑win_amd64.whl)
  - 아나콘다 콘솔에서 (pip install konlpy) 설치

In [70]:
import konlpy

In [74]:
from konlpy.tag import Okt
okt_tag = Okt()
okt_tag.morphs('질문이나 건의사항은 갓협 이슈 트래커에 남겨주세요.')

['질문', '이나', '건의', '사항', '은', '갓협', '이슈', '트래커', '에', '남겨주세요', '.']

In [75]:
cv = CountVectorizer(tokenizer=okt_tag.morphs) # 문장을 벡터로 변환할 때 단어 자르는 기능을 konlpy를 사용

In [87]:
sentences = ['안녕, 난 남자야 남자!', '안녕, 나는 여자야 여자!!']

In [88]:
cv.fit(sentences) # 토큰(단어)을 다 잘라서 어휘 사전(vocaburary)를 준비함.

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<bound method Okt.morphs of <konlpy.tag._okt.Okt object at 0x000001BE56FCB4A8>>,
        vocabulary=None)

In [91]:
cv.vocabulary_

{'안녕': 7,
 ',': 2,
 '난': 4,
 '남자': 5,
 '야': 8,
 '!': 0,
 '나': 3,
 '는': 6,
 '여자': 9,
 '!!': 1}

In [89]:
sparse_matrix = cv.transform(sentences) # 문장을 희소 행렬로 변환

In [90]:
sparse_matrix.toarray()

array([[1, 0, 1, 0, 1, 2, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 1, 1, 2]], dtype=int64)

## 네이버 영화 리뷰 추천/비추천 분류

In [94]:
import pandas as pd

In [105]:
movie = pd.read_csv('ratings_train.txt', delimiter='\t')
movie.shape

(150000, 3)

In [106]:
movie = movie.drop(columns='id')
movie = movie.dropna()

In [107]:
m = 1000
movie = movie.iloc[:m]

In [108]:
movie.head(2)

document  label
0                아 더빙.. 진짜 짜증나네요 목소리      0
1  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1

In [109]:
movie.shape

(1000, 2)

In [110]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 2 columns):
document    1000 non-null object
label       1000 non-null int64
dtypes: int64(1), object(1)
memory usage: 23.4+ KB


In [111]:
movie.isna().sum() # NAN이 있는지 확인(누락 확인)

document    0
label       0
dtype: int64

In [112]:
X = movie.document
y = movie.label

In [113]:
from konlpy.tag import Okt
cv = CountVectorizer(tokenizer=Okt().morphs)  # 전처리기

In [115]:
cv = cv.fit(X)

In [117]:
len(cv.vocabulary_)

4767

In [118]:
X_sm = cv.transform(X)

In [119]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression # 분류: classification

In [120]:
scores = cross_val_score(LogisticRegression(), X_sm, y, cv=3)
scores

C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.72754491, 0.71771772, 0.66366366])

In [121]:
scores.mean()

0.7029754305203407

In [156]:
model = LogisticRegression().fit(X_sm, y)

In [157]:
sentences = ['두시간 동안 잘 잤습니다.','돈 아까워요 ㅠㅠ', '너무 재미있어요!', '수면제','두번 봐라']
model.predict(cv.transform(sentences))

array([0, 0, 1, 0, 0], dtype=int64)

In [158]:
from sklearn.linear_model import RidgeClassifier # 분류: classification

In [159]:
scores2 = cross_val_score(RidgeClassifier(), X_sm, y, cv=3)
scores2

array([0.70658683, 0.6996997 , 0.66066066])

In [160]:
model2 = RidgeClassifier().fit(X_sm, y)

In [161]:
model2.predict(cv.transform(sentences))

array([0, 0, 1, 0, 1], dtype=int64)

In [148]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
cv2 = TfidfVectorizer(tokenizer=Okt().morphs, ngram_range=(1, 2))

In [149]:
cv2 = cv2.fit(X)

In [150]:
len(cv2.vocabulary_)

16350

In [151]:
X_sm2 = cv2.transform(X)

In [152]:
scores3 = cross_val_score(LogisticRegression(), X_sm2, y, cv=3)
scores3, scores3.mean()

C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


(array([0.71556886, 0.75375375, 0.69369369]), 0.7210054365742988)

In [164]:
model = LogisticRegression().fit(X_sm2, y)

In [165]:
model.predict(cv2.transform(sentences))

array([1, 0, 1, 0, 0], dtype=int64)